name: Deploy Ninescent Front

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # # Node 버전 지정 (GitHub Actions에서 Node 버전이 20)
    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 18.x
        
    # 1. 캐시 클린 및 패키지 정리
    - name: Clear NPM Cache
      run: |
        rm -rf node_modules
        npm cache clean --force
        
    # 2. 의존성 설치
    - name: Install Dependencies
      run: npm install
      
    # 3. 프론트엔드 빌드
    - name: Build Frontend
      run: npm run build

    # 4. 배포
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "dist/*"  # dist 내부 파일만 복사
        target: "/usr/share/nginx/html/"  # html 경로에 직접 복사

    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          sudo systemctl restart nginx
